name: "Tests"
description: 'Run Django Tests'
inputs:
  django_settings:
    description: 'Django Settings Module to use'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: psycopg2 prerequisites
      run: sudo apt-get install python-dev libpq-dev
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install "${{ matrix.django-version }}"
        python -m pip install django-translated-fields pytest-django pytest-cov pytest-factoryboy psycopg2-binary
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: set pythonpath
      run: |
        echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
    
    - name: Test with pytest
      run: |
        pytest -rs --nomigrations --cov --cov-branch
      env:
        DJANGO_SETTINGS_MODULE: ${{ inputs.django_settings }}
