# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ "*" ]

jobs:
  pg-build:

    runs-on: ubuntu-latest
    env:
      TOX_DB_NAME: letsagree
      TOX_DB_USER: postgres
      TOX_DB_PASSWD: ${{ secrets.PG_PASS }}
      TOX_DB_ENGINE: django.db.backends.postgresql
    
    services:
      postgres:
        image: postgres:13  # CHECK
        env:
          POSTGRES_PASSWORD: ${{ secrets.PG_PASS }}
          POSTGRES_USER: postgres
          POSTGRES_DB:: letsagree
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]  # CHECK
        django-version: ["Django>=2.2,<2.3", "Django>=3.1,<3.2"]    # CHECK
        django_settings: ["test_setup.settings", "test_setup.i18n_settings"]  # CHECK

    steps:
    - uses: actions/checkout@v2
    - name: Run Tests from action
      uses: ./.github/actions/run_tests.yml
      with:
        django_settings: ${{ matrix.django_settings }}
       
    - name: Install last pass dependencies
      if: matrix.python-version == 3.9  # CHECK
      run: |
        python -m pip install black flake8 bandit

        
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: Testing
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
  coveralls_finish:
    needs: pg-build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
